version: '2'
services:
    webserver:
        image: opentrials/opentrials-airflow
        restart: always
        environment:
            EXECUTOR:
            AIRFLOW_ENABLE_AUTH:
            STATSD_ENABLED:
            REMOTE_BASE_LOG_FOLDER:
            REMOTE_LOG_CONN_ID:
            FERNET_KEY:
            DB_URI:
            DB_USER:
            DB_PASSWORD:
            DB_TABLE:
            SMTP_HOST:
            SMTP_USER:
            SMTP_PASSWORD:
        ports:
            - "8080:8080"
        command: webserver

    scheduler:
        image: opentrials/opentrials-airflow
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        depends_on:
            - webserver
        environment:
            EXECUTOR:
            AIRFLOW_ENABLE_AUTH:
            STATSD_ENABLED:
            REMOTE_BASE_LOG_FOLDER:
            REMOTE_LOG_CONN_ID:
            FERNET_KEY:
            DB_URI:
            DB_USER:
            DB_PASSWORD:
            DB_TABLE:
            SMTP_HOST:
            SMTP_USER:
            SMTP_PASSWORD:
        command: ['scheduler', '--num_runs', '10']
